version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --statsd-address=graphite:8125 --statsd-interval="60s" --statsd-mem-stats=true
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161 --graphite-url=http://127.0.0.1:81
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"

  graphite:
    image: hopsoft/graphite-statsd
    #command: --restart=always
    ports: 
      - "80:80"
      - "81:81"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"